### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by stevenvachon** [acusti/onscrolling#4]
I doubt this is beta anymore.

**Comment by acusti** [comment]
Good point 😄! The main feature I want to add before releasing 1.0.0 is:

> Expose measure and mutate functions to attach handlers specifically to the measuring (read) or mutating (write) portion of each cycle to minimize layout calculations

But I was planning to make that an addition to the existing API, so shouldn’t require a major version update.

**Comment by Textras** [comment]
Curious, @acusti did you migrate to another lib like FastDOM?

**Comment by acusti** [comment]
@Textras no, i’m still using this library. it’s stable, i just haven’t made the version bump to 1.0.
